# pagerduty oncall utility handler
service: pd-oncall 

provider:
  name: aws
  runtime: python3.6
  region: ap-southeast-2
  stage: production
  iamRoleStatements:
   - Effect: "Allow"
     Action: "secretsmanager:GetSecretValue"
     Resource:
      - 'Fn::Join':
        - ':'
        -
          - 'arn:aws:secretsmanager'
          - Ref: 'AWS::Region'
          - Ref: 'AWS::AccountId'
          - 'secret:pagerduty-gVcp4A'

functions:
  main:
    handler: handler.do
    events:
      - schedule: cron(0 22 * * ? *)

package:
  exclude:
    - node_modules/**
    - venv/**
    - package-lock.json
    - package.json


plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true